// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DataAccess;

#nullable disable

namespace TaskAPI.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20240102103333_AuthorEntityAndData")]
    partial class AuthorEntityAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Kavinda Bandara"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Shakuni Samanmalee"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Sam Don Karunarathne"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Harshana Disanayake"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorId = 1,
                            Created = new DateTime(2024, 1, 2, 16, 3, 33, 74, DateTimeKind.Local).AddTicks(2374),
                            Description = "You need to get your book",
                            Due = new DateTime(2024, 1, 7, 16, 3, 33, 74, DateTimeKind.Local).AddTicks(2390),
                            Status = 0,
                            Title = "Get Books for the school"
                        },
                        new
                        {
                            ID = 2,
                            AuthorId = 1,
                            Created = new DateTime(2024, 1, 2, 16, 3, 33, 74, DateTimeKind.Local).AddTicks(2397),
                            Description = "You need to Super market",
                            Due = new DateTime(2024, 1, 7, 16, 3, 33, 74, DateTimeKind.Local).AddTicks(2397),
                            Status = 0,
                            Title = "Need to Vegitable - DB"
                        },
                        new
                        {
                            ID = 3,
                            AuthorId = 2,
                            Created = new DateTime(2024, 1, 2, 16, 3, 33, 74, DateTimeKind.Local).AddTicks(2400),
                            Description = "You need to go to Studio",
                            Due = new DateTime(2024, 1, 7, 16, 3, 33, 74, DateTimeKind.Local).AddTicks(2400),
                            Status = 0,
                            Title = "Need to Camera - DB"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
