// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DataAccess;

#nullable disable

namespace TaskAPI.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressNo = "45",
                            City = "Alawwa",
                            FullName = "Kavinda Bandara",
                            Street = "Street 1"
                        },
                        new
                        {
                            Id = 2,
                            AddressNo = "21",
                            City = "Jaffna",
                            FullName = "Shakuni Samanmalee",
                            Street = "Street 2"
                        },
                        new
                        {
                            Id = 3,
                            AddressNo = "72",
                            City = "Kurunegala",
                            FullName = "Sam Don Karunarathne",
                            Street = "Street 3"
                        },
                        new
                        {
                            Id = 4,
                            AddressNo = "55",
                            City = "Negombo",
                            FullName = "Harshana Disanayake",
                            Street = "Street 1"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorId = 1,
                            Created = new DateTime(2024, 1, 5, 9, 1, 35, 78, DateTimeKind.Local).AddTicks(5118),
                            Description = "You need to get your book",
                            Due = new DateTime(2024, 1, 10, 9, 1, 35, 78, DateTimeKind.Local).AddTicks(5135),
                            Status = 0,
                            Title = "Get Books for the school"
                        },
                        new
                        {
                            ID = 2,
                            AuthorId = 1,
                            Created = new DateTime(2024, 1, 5, 9, 1, 35, 78, DateTimeKind.Local).AddTicks(5142),
                            Description = "You need to Super market",
                            Due = new DateTime(2024, 1, 10, 9, 1, 35, 78, DateTimeKind.Local).AddTicks(5143),
                            Status = 0,
                            Title = "Need to Vegitable - DB"
                        },
                        new
                        {
                            ID = 3,
                            AuthorId = 2,
                            Created = new DateTime(2024, 1, 5, 9, 1, 35, 78, DateTimeKind.Local).AddTicks(5145),
                            Description = "You need to go to Studio",
                            Due = new DateTime(2024, 1, 10, 9, 1, 35, 78, DateTimeKind.Local).AddTicks(5146),
                            Status = 0,
                            Title = "Need to Camera - DB"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany("Todos")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
